name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Syntax check
      run: cargo check --all-targets --workspace

    - name: Lint check
      run: cargo clippy --all-targets --workspace

    - name: Run tests
      run: cargo test --workspace

    - name: Run format check
      run: cargo fmt --check --all
